import '@fortawesome/fontawesome-svg-core/styles.css'
import {
  faShrimp, faBuildingColumns, faAnchor, faEnvelopeOpenText,
  faUser as faUserNoCircle, faHeart, faStar, faFan, faQuoteLeft, faQuoteRight, faClipboardCheck,
  faCircleQuestion as solidCircleQuestion, faCircleUser as solidCircleUser, faQrcode, faFileArrowDown,
  faMessage, faEnvelope, faCalendar as solidCalendar, faBuilding as solidBuilding, faHandshake as solidHandshake,
  faShareNodes, faFishFins, faLifeRing, faMapLocationDot, faCubes, faCheckCircle as solidCirChk,
  faCalendarDays, faUserGroup, faMinusCircle, faPlusCircle, faCompass, faShoppingCart, faChild,
  faXmark, faCheck, faChevronDown, faChevronLeft, faChevronRight, faCloudArrowUp, faDollarSign,
  faBars, faHouse, faPenRuler, faGear, faPenToSquare, faPlus, faArrowRight, faArrowLeft,
  faBullhorn, faUsers, faUserPlus, faPersonCirclePlus, faArrowUpFromBracket, faEllipsisV,
  faRightFromBracket, faCircleExclamation, faTriangleExclamation, faMagnifyingGlass, faCircleInfo,
  faCloudDownload, faDownload, faArrowsRotate, faWrench, faBan, faPhone, faArrowUpRightFromSquare,
  faListCheck, faList, faCircleNotch, faEye, faUserTie, faUserPen, faKey, faShip, faLock, faEarthAmericas,
  faPalette, faCalendarCheck, faLink, faClock, faSquarePlus, faBell as faBellSolid, faLocationDot, faCreditCard,
  faRightLeft, faComment as faCommentSolid, faReceipt, faCopy, faPercent, faArrowTurnUp, faArrowTurnDown,
  faTag, faMoon, faSun,
} from '@fortawesome/free-solid-svg-icons';
import {
  faCheckCircle, faCalendarMinus, faBuilding, faComment,
  faCalendar, faCircleUser, faHandshake, faBell, faTrashCan, faImage, faCircleQuestion,
  faCircleCheck, faCalendarPlus, faCalendarXmark, faAddressCard, faPaperPlane, faCircle,
} from '@fortawesome/free-regular-svg-icons';
import { config, library } from "@fortawesome/fontawesome-svg-core";
import { faGoogle, faGithub, faLinkedin, faGitlab } from '@fortawesome/free-brands-svg-icons';

/**
 * @see https://fontawesome.com/search?o=r&m=free
 */
export const AppFontAwesomeIcons = {
  AddressCard: faAddressCard,
  Anchor: faAnchor,
  ArrowRight: faArrowRight,
  ArrowLeft: faArrowLeft,
  ArrowsRotate: faArrowsRotate,
  ArrowTurnUp: faArrowTurnUp,
  ArrowTurnDown: faArrowTurnDown,
  Share: faArrowUpRightFromSquare,
  ShareNodes: faShareNodes,
  IOSShare: faArrowUpFromBracket,
  Ban: faBan,
  Bank: faBuildingColumns,
  Bell: faBell,
  BellSolid: faBellSolid,
  Building: faBuilding,
  BuildingSolid: solidBuilding,
  BullHorn: faBullhorn, // Cool alert icon?
  Calendar: faCalendar,
  CalendarSolid: solidCalendar,
  CalendarCheck: faCalendarCheck,
  CalendarDays: faCalendarDays,
  CalendarPlus: faCalendarPlus,
  CalendarMinus: faCalendarMinus,
  CalendarXmark: faCalendarXmark,
  Cart: faShoppingCart,
  Chat: faMessage,
  Check: faCheck,
  CheckCircle: faCheckCircle,
  ChevronDown: faChevronDown,
  ChevronLeft: faChevronLeft,
  ChevronRight: faChevronRight,
  Child: faChild,
  Compass: faCompass,
  Circle: faCircle,
  CircleNotch: faCircleNotch,
  CircleCheck: faCircleCheck,
  CircleCheckSolid: solidCirChk,
  CircleExclamation: faCircleExclamation,
  CircleInfo: faCircleInfo,
  CircleQuestion: faCircleQuestion,
  CircleQuestionSolid: solidCircleQuestion,
  ClipboardCheck: faClipboardCheck,
  Clock: faClock,
  CloudArrowUp: faCloudArrowUp,
  CloudDownload: faCloudDownload,
  Comment: faComment,
  CommentSolid: faCommentSolid,
  Copy: faCopy,
  CreditCard: faCreditCard,
  Cubes: faCubes,
  DollarSign: faDollarSign,
  Download: faDownload,
  DownloadFile: faFileArrowDown,
  EllipsisV: faEllipsisV,
  Earth: faEarthAmericas,
  Envelope: faEnvelope,
  Eye: faEye,
  Floaty: faLifeRing,
  FishFins: faFishFins,
  Gear: faGear,
  Google: faGoogle,
  Handshake: faHandshake,
  HandshakeSolid: solidHandshake,
  Heart: faHeart,
  Home: faHouse,
  Image: faImage,
  Key: faKey,
  Link: faLink,
  List: faList,
  ListCheck: faListCheck,
  LifeRing: faLifeRing,
  Lock: faLock,
  Location: faLocationDot,
  Logout: faRightFromBracket,
  MailOpen: faEnvelopeOpenText,
  Magnifying: faMagnifyingGlass,
  MapLocation: faMapLocationDot,
  Menu: faBars,
  MinusCircle: faMinusCircle,
  Palette: faPalette,
  PaperPlane: faPaperPlane,
  PenAndRuler: faPenRuler,
  PenToSquare: faPenToSquare,
  Percent: faPercent,
  PersonCirclePlus: faPersonCirclePlus,
  Phone: faPhone,
  Plus: faPlus,
  PlusCircle: faPlusCircle,
  Propeller: faFan,
  Receipt: faReceipt,
  RightLeft: faRightLeft,
  Ship: faShip,
  Shrimp: faShrimp,
  Spinner: faCircleNotch, // faSpinner
  SquarePlus: faSquarePlus,
  Star: faStar,
  Tag: faTag,
  Trash: faTrashCan,
  TriangleExclamation: faTriangleExclamation,
  QRCode: faQrcode,
  QuoteLeft: faQuoteLeft,
  QuoteRight: faQuoteRight,
  User: faCircleUser,
  UserNoCircle: faUserNoCircle,
  UserSolid: solidCircleUser,
  UserGroup: faUserGroup,
  UserPen: faUserPen,
  UserTie: faUserTie,
  Users: faUsers,
  UserPlus: faUserPlus,
  Wrench: faWrench,
  X: faXmark,
  Moon: faMoon,
  Sun: faSun,
  GitHub: faGithub,
  LinkedIn: faLinkedin,
  GitLab: faGitlab,
}

export function faInit() {
  Object.values(AppFontAwesomeIcons).forEach(definition => library.add(definition))
  config.autoAddCss = false
}